### ISSUE TITLE
Crear canal tipo patchbot

### ISSUE THREAD

**Issue by hugosajama-ae** [guidospadavecchia/DolarBot#4]
Hola hay alguna manera de crear un canal donde el bot mande un mensaje cada vez que el dolar cambia? tipo patchbot

![image](https://github.com/guidospadavecchia/DolarBot/assets/131486991/45488ec1-c7cd-4435-b23a-9be633b39b15)

**Comment by guidospadavecchia** [comment]
Hola!

Por el momento no he desarrollado esa funcionalidad, porque para esto DolarBot debería implementar una base de datos (para guardar datos acerca de a que servidor enviar las alertas, en que horario, etcétera), cosa que hoy en día no sucede, más que nada por una cuestión de costos de servidores y mantenimiento (hoy en día, DolarBot se hostea gratuitamente, y agregar una base de datos tendría un costo).
Lo cual no significa que no haya considerado desarrollar esta funcionalidad, ni que no vaya a implementarse en el futuro.
